/// The strong, mixed and irregular verbs' past stems (#1223), written by the
/// team, so no dictionary licence is needed: infinitive → (Präteritum,
/// Konjunktiv II), each as the 1st/3rd person singular.
///
/// A prefixed or separable verb takes its base's row: verstehen is ver +
/// stehen (verstand), ankommen is an + kommen (kam … an, ankam). Verbs that
/// are weak in their common sense (schaffen "manage", bewegen) are left out,
/// so the rules give them -te.
library;

const Map<String, (String, String)> strongVerbs = <String, (String, String)>{
  'befehlen': ('befahl', 'beföhle'),
  'beginnen': ('begann', 'begänne'),
  'beißen': ('biss', 'bisse'),
  'bergen': ('barg', 'bärge'),
  'betrügen': ('betrog', 'betröge'),
  'biegen': ('bog', 'böge'),
  'bieten': ('bot', 'böte'),
  'binden': ('band', 'bände'),
  'bitten': ('bat', 'bäte'),
  'blasen': ('blies', 'bliese'),
  'bleiben': ('blieb', 'bliebe'),
  'braten': ('briet', 'briete'),
  'brechen': ('brach', 'bräche'),
  'brennen': ('brannte', 'brennte'),
  'bringen': ('brachte', 'brächte'),
  'denken': ('dachte', 'dächte'),
  'dringen': ('drang', 'dränge'),
  'dürfen': ('durfte', 'dürfte'),
  'empfehlen': ('empfahl', 'empfähle'),
  'erschrecken': ('erschrak', 'erschräke'),
  'essen': ('aß', 'äße'),
  'fahren': ('fuhr', 'führe'),
  'fallen': ('fiel', 'fiele'),
  'fangen': ('fing', 'finge'),
  'finden': ('fand', 'fände'),
  'fliegen': ('flog', 'flöge'),
  'fliehen': ('floh', 'flöhe'),
  'fließen': ('floss', 'flösse'),
  'fressen': ('fraß', 'fräße'),
  'frieren': ('fror', 'fröre'),
  'geben': ('gab', 'gäbe'),
  'gedeihen': ('gedieh', 'gediehe'),
  'gehen': ('ging', 'ginge'),
  'gelingen': ('gelang', 'gelänge'),
  'gelten': ('galt', 'gälte'),
  'genießen': ('genoss', 'genösse'),
  'geschehen': ('geschah', 'geschähe'),
  'gewinnen': ('gewann', 'gewänne'),
  'gießen': ('goss', 'gösse'),
  'gleichen': ('glich', 'gliche'),
  'gleiten': ('glitt', 'glitte'),
  'graben': ('grub', 'grübe'),
  'greifen': ('griff', 'griffe'),
  'haben': ('hatte', 'hätte'),
  'halten': ('hielt', 'hielte'),
  'hängen': ('hing', 'hinge'),
  'heben': ('hob', 'höbe'),
  'heißen': ('hieß', 'hieße'),
  'helfen': ('half', 'hülfe'),
  'kennen': ('kannte', 'kennte'),
  'klingen': ('klang', 'klänge'),
  'kommen': ('kam', 'käme'),
  'können': ('konnte', 'könnte'),
  'kriechen': ('kroch', 'kröche'),
  'laden': ('lud', 'lüde'),
  'lassen': ('ließ', 'ließe'),
  'laufen': ('lief', 'liefe'),
  'leiden': ('litt', 'litte'),
  'leihen': ('lieh', 'liehe'),
  'lesen': ('las', 'läse'),
  'liegen': ('lag', 'läge'),
  'lügen': ('log', 'löge'),
  'meiden': ('mied', 'miede'),
  'messen': ('maß', 'mäße'),
  'mögen': ('mochte', 'möchte'),
  'müssen': ('musste', 'müsste'),
  'nehmen': ('nahm', 'nähme'),
  'nennen': ('nannte', 'nennte'),
  'pfeifen': ('pfiff', 'pfiffe'),
  'preisen': ('pries', 'priese'),
  'raten': ('riet', 'riete'),
  'reiben': ('rieb', 'riebe'),
  'reißen': ('riss', 'risse'),
  'reiten': ('ritt', 'ritte'),
  'rennen': ('rannte', 'rennte'),
  'riechen': ('roch', 'röche'),
  'ringen': ('rang', 'ränge'),
  'rufen': ('rief', 'riefe'),
  'saufen': ('soff', 'söffe'),
  'scheiden': ('schied', 'schiede'),
  'scheinen': ('schien', 'schiene'),
  'schieben': ('schob', 'schöbe'),
  'schießen': ('schoss', 'schösse'),
  'schlafen': ('schlief', 'schliefe'),
  'schlagen': ('schlug', 'schlüge'),
  'schleichen': ('schlich', 'schliche'),
  'schließen': ('schloss', 'schlösse'),
  'schmeißen': ('schmiss', 'schmisse'),
  'schmelzen': ('schmolz', 'schmölze'),
  'schneiden': ('schnitt', 'schnitte'),
  'schreiben': ('schrieb', 'schriebe'),
  'schreien': ('schrie', 'schriee'),
  'schreiten': ('schritt', 'schritte'),
  'schweigen': ('schwieg', 'schwiege'),
  'schwimmen': ('schwamm', 'schwömme'),
  'schwinden': ('schwand', 'schwände'),
  'schwingen': ('schwang', 'schwänge'),
  'schwören': ('schwor', 'schwüre'),
  'sehen': ('sah', 'sähe'),
  'sein': ('war', 'wäre'),
  'senden': ('sandte', 'sendete'),
  'singen': ('sang', 'sänge'),
  'sinken': ('sank', 'sänke'),
  'sitzen': ('saß', 'säße'),
  'sollen': ('sollte', 'sollte'),
  'sprechen': ('sprach', 'spräche'),
  'springen': ('sprang', 'spränge'),
  'stechen': ('stach', 'stäche'),
  'stehen': ('stand', 'stünde'),
  'stehlen': ('stahl', 'stähle'),
  'steigen': ('stieg', 'stiege'),
  'sterben': ('starb', 'stürbe'),
  'stinken': ('stank', 'stänke'),
  'stoßen': ('stieß', 'stieße'),
  'streichen': ('strich', 'striche'),
  'streiten': ('stritt', 'stritte'),
  'tragen': ('trug', 'trüge'),
  'treffen': ('traf', 'träfe'),
  'treiben': ('trieb', 'triebe'),
  'treten': ('trat', 'träte'),
  'trinken': ('trank', 'tränke'),
  'tun': ('tat', 'täte'),
  'verderben': ('verdarb', 'verdürbe'),
  'vergessen': ('vergaß', 'vergäße'),
  'verlieren': ('verlor', 'verlöre'),
  'verzeihen': ('verzieh', 'verziehe'),
  'wachsen': ('wuchs', 'wüchse'),
  'waschen': ('wusch', 'wüsche'),
  'weichen': ('wich', 'wiche'),
  'weisen': ('wies', 'wiese'),
  'wenden': ('wandte', 'wendete'),
  'werben': ('warb', 'würbe'),
  'werden': ('wurde', 'würde'),
  'werfen': ('warf', 'würfe'),
  'wiegen': ('wog', 'wöge'),
  'wissen': ('wusste', 'wüsste'),
  'wollen': ('wollte', 'wollte'),
  'ziehen': ('zog', 'zöge'),
  'zwingen': ('zwang', 'zwänge'),
};

/// The forms no rule makes from a verb's infinitive, its 3rd person and its
/// past (#1274): sein's present, werden's «wirst», and werden's participle
/// in the passive («ist gemacht worden»).
const Map<String, List<String>> irregularForms = <String, List<String>>{
  'sein': <String>['bin', 'bist', 'sind', 'seid'],
  'werden': <String>['wirst', 'worden'],
};
