@TestOn('vm')
library;

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// `content_schema.drift` mirrors the DDL `make content` writes.
///
/// It exists so drift can type-check the queries in `content.drift`. A mirror
/// that has drifted type-checks against a schema the pipeline does not
/// produce, and then every query compiles and fails at run time — which is the
/// one failure mode this file is meant to remove.
///
/// It is generated by `make gen` from the two `.sql` files, so this test is
/// the thing that notices when someone edits the mirror instead.
void main() {
  final mirror = File('lib/data/db/content_schema.drift').readAsStringSync();
  final source =
      File('../tools/content_schema.sql').readAsStringSync() +
      File('../tools/content_fts.sql').readAsStringSync();

  /// Statements, stripped of comments and collapsed whitespace, so a reflowed
  /// comment in one file does not read as a schema change.
  List<String> statements(String sql) {
    final withoutComments = sql
        .split('\n')
        .where((line) => !line.trimLeft().startsWith('--'))
        .join('\n');
    return <String>[
      for (final part in withoutComments.split(';'))
        if (part.trim().isNotEmpty)
          part.replaceAll(RegExp(r'\s+'), ' ').trim().toLowerCase(),
    ];
  }

  test('both files were found and are not empty', () {
    // Everything below compares the two; a missing file would make each
    // assertion pass on nothing.
    expect(statements(mirror), isNotEmpty);
    expect(statements(source), isNotEmpty);
  });

  test('the mirror is statement-for-statement the pipeline DDL', () {
    expect(
      statements(mirror),
      statements(source),
      reason:
          'content_schema.drift is generated by `make gen` from '
          'tools/content_schema.sql and tools/content_fts.sql. Edit those, '
          'then regenerate — never this file.',
    );
  });

  test('it says where it comes from', () {
    // The next person to open it reaches for it because a query does not
    // compile; the header is what stops them fixing it here.
    expect(mirror, contains('GENERATED'));
    expect(mirror, contains('tools/content_schema.sql'));
  });

  test('every table the queries read is declared', () {
    final queries = File('lib/data/db/content.drift').readAsStringSync();
    final declared = <String>{
      for (final match in RegExp(
        r'CREATE (?:VIRTUAL )?TABLE (\w+)',
        caseSensitive: false,
      ).allMatches(mirror))
        match.group(1)!.toLowerCase(),
    };

    final read = <String>{
      for (final match in RegExp(
        r'\b(?:FROM|JOIN)\s+(\w+)',
        caseSensitive: false,
      ).allMatches(queries))
        match.group(1)!.toLowerCase(),
    };

    expect(
      read.difference(declared),
      isEmpty,
      reason: 'content.drift reads tables the mirror does not declare',
    );
  });
}
